FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install -r /code/requirements.txt

COPY ./src/api.py /code/src/

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0"]
