services:
  mlflow:
    image: "ghcr.io/mlflow/mlflow:v2.16.2"
    ports:
      - "5001:5000"
    volumes:
      - "./mlflow:/mlruns"
      - "./mlartifacts:/mlartifacts"
    command: ["mlflow" , "ui" , "--host" , "0.0.0.0"]
  airflow-web-server:
    image: "apache/airflow:2.10.2-python3.10"
    user: "0:0"
    ports:
      - "5002:8080"
    volumes:
      - "./airflow:/opt/airflow"
    command: ["airflow", "webserver"]
  airflow-scheduler:
    build:
      context: "."
      dockerfile: "Dockerfile.mlops_airflow"
    image: "mlops_airflow:latest"
    user: "airflow"
    volumes:
      - "./airflow:/opt/airflow"
    depends_on:
      - "airflow-web-server"
    command: ["airflow", "scheduler"]
  api:
    build:
      context: "."
      dockerfile: "Dockerfile.mlops_api"
    image: "mlops_api:latest"
    ports:
      - "8000:8000"
