digest: 30611e7b
name: dataset
profile: '{"features_shape": [30, 4], "features_size": 120, "features_nbytes": 960}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float64\", \"shape\": [-1, 4]}}]", "targets": null}}'
source: '{"tags": {"mlflow.user": "deptno", "mlflow.source.name": "/Users/deptno/.local/data/virtualenvs/ml-project-ml-pjt-2-EwcpbH9v/lib/python3.10/site-packages/ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
